#ifndef ANT_SPRITEENUM_H
#define ANT_SPRITEENUM_H


enum TileEnum {
    BASIC_FLOOR = 0,
    ROCK_FLOOR = 5,
    COLONY_FLOOR = 9,
    FOOD_LAYER = 10,
    BIG_FOOD_LAYER = 11,
    CLOUD_LAYER = 14,
    QUEEN = 24,
    SCOOT_ANT = 15,
    SOLDIER_ANT = 25,
    WORKER_ANT = 35,
    SLAVEOWNER_ANT = 45,

    FIRST_PHEROMONE_LEVEL = 55
};

#endif
