#include "../header/Config.h"

Config::DEFAULT_FOOD_CONSUMING_TICK = 0.001;
Config::DEFAULT_DAY_BEFORE_DEATH = 365;

Config::NEW_ANT_EVERY_DAY = 2;
Config::QUEEN_FOOD_CONSUMING_TICK = 0.01;
Config::QUEEN_DAY_BEFORE_DEATH = 365000;

Config::WORKER_DAY_BEFORE_ADULT = 15;
Config::WORKER_MAX_FOOD_CARRIED_AMOUNT = 1;

Config::SCOOT_DAY_BEFORE_ADULT = 2;

Config::SOLDIER_DAY_BEFORE_VISITE_COLONY = 100;

Config::SLAVE_OWNER_MAX_DAY_SURVIVE_BEFORE_FEEDING = 10;

Config::ROCK_MAX_ANT_ON_CELL = 0;
Config::BASIC_CELL_MAX_ANT_ON_CELL = 12;
Config::COLONY_MAX_ANT_ON_CELL = 100;

Config::ROCK_PERCENT = 0.3;
Config::ROCK_SIZE_ONE_PERCENT = 0.5;
Config::ROCK_SIZE_TWO_PERCENT = 0.3;
Config::ROCK_SIZE_THREE_PERCENT = 0.1;
Config::ROCK_SIZE_FOUR_PERCENT = 0.5;
Config::ROCK_SIZE_FIVE_PERCENT = 0.4;
Config::ROCK_SIZE_SIZE_PERCENT = 0.1;

Config::FOOD_CASE_NUMER_PERCENT = 0.0002;
Config::FOOD_UNIT_VALUE = 10;

Config::LENGTH = 211;
Config::HEIGHT = 201;
