#include "../header/Config.h"

double Config::DEFAULT_FOOD_CONSUMING_TICK = 0.001;
int Config::DEFAULT_HOURS_BEFORE_DEATH = 365 * 24;

int Config::NEW_ANT_EVERY_DAY = 2;
double Config::QUEEN_FOOD_CONSUMING_TICK = 0.01;
int Config::QUEEN_HOURS_BEFORE_DEATH = 365 * 10 * 24;

int Config::WORKER_HOURS_BEFORE_ADULT = 15 * 24;
int Config::WORKER_MAX_FOOD_CARRIED_AMOUNT = 1;

int Config::SCOOT_HOURS_BEFORE_ADULT = 2 * 24;

int Config::SOLDIER_HOURS_BEFORE_VISIT_COLONY = 100 * 24;

int Config::SLAVE_OWNER_MAX_HOURS_SURVIVE_BEFORE_FEEDING = 10;

int Config::ROCK_MAX_ANT_ON_CELL = 0;
int Config::BASIC_CELL_MAX_ANT_ON_CELL = 12;
int Config::COLONY_MAX_ANT_ON_CELL = 100;

double Config::ROCK_PERCENT = 0.3;
double Config::ROCK_SIZE_ONE_PERCENT = 0.5;
double Config::ROCK_SIZE_TWO_PERCENT = 0.3;
double Config::ROCK_SIZE_THREE_PERCENT = 0.1;
double Config::ROCK_SIZE_FOUR_PERCENT = 0.5;
double Config::ROCK_SIZE_FIVE_PERCENT = 0.4;
double Config::ROCK_SIZE_SIZE_PERCENT = 0.1;

double Config::FOOD_CASE_NUMBER_PERCENT = 0.0002;
int Config::FOOD_UNIT_VALUE = 10;

int Config::LENGTH = 211;
int Config::HEIGHT = 201;
